import type { Part } from "./types";

export const parts: Part[] = [
  { partNumber: "E2E-X5ME1", slug: "e2e-x5me1", brand: "Omron", model: "E2E inductive proximity sensor", specs: ["Inductive proximity sensing", "Common M12 style application", "Machine automation replacement"], applications: ["Position detection", "Machine interlock", "Conveyor sensing"], industries: ["textile-mills", "food-processing"], compatibility: ["Omron E2E sensor families", "Industrial control panels"] },
  { partNumber: "CP1E-N40", slug: "cp1e-n40", brand: "Omron", model: "CP1E PLC", specs: ["Compact PLC family", "Machine control", "I/O expansion capable depending on variant"], applications: ["Machine sequencing", "Panel replacement", "Automation control"], industries: ["sugar-mills", "pharmaceutical-plants"], compatibility: ["Omron CP1E systems", "PLC control panels"] },
  { partNumber: "3RV2031-4WA10", slug: "3rv2031-4wa10", brand: "Siemens", model: "Motor protection circuit breaker", specs: ["Motor protection", "Control panel component", "Industrial switching gear"], applications: ["Motor feeders", "Pump panels", "Machine panels"], industries: ["cement-plants", "textile-mills"], compatibility: ["Motor starter assemblies", "Industrial panels"] },
  { partNumber: "PNOZ X3", slug: "pnoz-x3", brand: "Pilz", model: "Safety relay", specs: ["Safety relay", "Emergency stop and safety gate circuits", "Machine safety application"], applications: ["Machine guarding", "Emergency stops", "Safety control panels"], industries: ["textile-mills", "food-processing"], compatibility: ["Pilz safety circuits", "Industrial safety panels"] },
  { partNumber: "DPA51CM44", slug: "dpa51cm44", brand: "Carlo Gavazzi", model: "Phase monitoring relay", specs: ["Phase monitoring", "Voltage supervision", "Panel protection"], applications: ["Motor protection", "Panel alarms", "Phase failure detection"], industries: ["sugar-mills", "cement-plants"], compatibility: ["Three-phase panels", "Motor control centers"] },
  { partNumber: "7/.036 4-Core PVC/PVC Copper Conductor Cable", slug: "7-036-4-core-pvc-copper-conductor-cable", brand: "General Industrial", model: "PVC/PVC copper conductor cable", specs: ["7/.036 copper conductor", "4-core cable", "PVC/PVC insulation"], applications: ["Industrial wiring", "Control panels", "Machine electrical work"], industries: ["sugar-mills", "textile-mills", "cement-plants"], compatibility: ["Industrial wiring systems", "Control panels"] }
];
