import type { Product } from "./types";

export const products: Product[] = [
  { slug: "plc", name: "PLCs", description: "Programmable logic controllers for plant automation, machine control and replacement panels.", applications: ["Machine automation", "Process control", "Panel upgrades"], industries: ["sugar-mills", "textile-mills", "pharmaceutical-plants"], brands: ["Omron", "Fuji Electric"] },
  { slug: "sensors", name: "Industrial Sensors", description: "Proximity, photoelectric, ultrasonic, area, fiber optic and fork sensors.", applications: ["Object detection", "Position sensing", "Conveyor automation"], industries: ["textile-mills", "food-processing", "cement-plants"], brands: ["Omron", "Datasensing", "Carlo Gavazzi", "Xecro"] },
  { slug: "safety-relays", name: "Safety Relays", description: "Safety relays, controllers and non-contact safety sensors for machinery protection.", applications: ["Emergency stop circuits", "Safety gates", "Machine guarding"], industries: ["textile-mills", "pharmaceutical-plants", "food-processing"], brands: ["Pilz", "Omron"] },
  { slug: "circuit-breakers", name: "Circuit Breakers", description: "MCCB, MCB and MPCB protection devices for control panels and machinery.", applications: ["Panel protection", "Motor protection", "Distribution boards"], industries: ["sugar-mills", "cement-plants", "fertilizer-industry"], brands: ["Eaton", "Fuji Electric"] },
  { slug: "magnetic-contactors", name: "Magnetic Contactors & Overload Relays", description: "Contactors and thermal overload relays for motor switching and protection.", applications: ["Motor starters", "Pump panels", "Crane panels"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Fuji Electric", "Eaton"] },
  { slug: "dol-starters", name: "DOL & Starters", description: "Direct-on-line starters and control gear for industrial motors.", applications: ["Motor starting", "Pump control", "Machine panels"], industries: ["textile-mills", "food-processing", "fertilizer-industry"], brands: ["Fuji Electric", "Eaton"] },
  { slug: "pressure-switches", name: "Pressure Switches & Transmitters", description: "Pressure switches and transmitters for air, water, oil, steam and process fluids.", applications: ["Pump protection", "Process measurement", "Hydraulic systems"], industries: ["pharmaceutical-plants", "food-processing", "fertilizer-industry"], brands: ["Eaton", "Huba Control", "Fantini Cosmi"] },
  { slug: "flow-switches", name: "Flow Switches", description: "Air and water flow switches for equipment protection and process monitoring.", applications: ["Cooling water checks", "Air flow supervision", "Pump systems"], industries: ["cement-plants", "food-processing"], brands: ["Carlo Gavazzi", "Huba Control"] },
  { slug: "encoders", name: "Rotary & Linear Encoders", description: "Rotary and linear encoder sourcing for speed, position and synchronization.", applications: ["Centrifugal machines", "Conveyors", "Position feedback"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Hohner Encoders", "Lika Electronics"] },
  { slug: "burner-controls", name: "Burner Controls", description: "Burner controllers, ignition relays, solenoid valves, UV sensors and photo-diodes.", applications: ["Boiler burners", "Industrial ovens", "Flame supervision"], industries: ["food-processing", "textile-mills", "cement-plants"], brands: ["Brahma", "Cofi Ignitions"] },
  { slug: "level-switches", name: "Level Switches & Relays", description: "Float switches, floatless level relays, electrode holders and rotary level controls.", applications: ["Tank level control", "Silo level detection", "Pump automation"], industries: ["food-processing", "cement-plants", "fertilizer-industry"], brands: ["Riko Float Switches", "Carlo Gavazzi"] },
  { slug: "monitoring-relays", name: "Monitoring Relays", description: "Phase, voltage, thermistor and process monitoring relays.", applications: ["Motor protection", "Voltage supervision", "Panel alarms"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Eaton", "Carlo Gavazzi"] },
  { slug: "timers-counters", name: "Timers & Counters", description: "Industrial timers and counters for automation panels and machine sequencing.", applications: ["Batch counting", "Delay timing", "Control sequencing"], industries: ["textile-mills", "food-processing"], brands: ["Omron", "Shinko"] },
  { slug: "transmitters", name: "Transmitters & Process Controllers", description: "Flow, pressure, temperature and process transmitters and controllers.", applications: ["Process indication", "Control loops", "Plant instrumentation"], industries: ["pharmaceutical-plants", "fertilizer-industry", "food-processing"], brands: ["Datexel", "Huba Control", "Ascon Tecnologic"] }
];
