import type { Product } from "./types";

export const productCategories = [
  "Sugar Mill & Process Equipment",
  "Electrical Components",
  "Valves & Flow Control",
  "Sensors",
  "Safety Systems",
  "Control Systems",
  "Encoders & Measurement",
  "Accessories",
  "Drives & Motion",
  "Process Instrumentation"
] as const;

export const products: Product[] = [
  { slug: "centrifugal-machines", name: "Centrifugal Machines (Sugar / Refinery)", category: "Sugar Mill & Process Equipment", description: "Centrifugal machine parts and sourcing support for sugar mills and refinery process equipment.", applications: ["Sugar refining", "Crystal separation", "Mill process equipment"], industries: ["sugar-mills"], brands: ["Hohner Encoders", "Lika Electronics", "Omron"] },
  { slug: "batch-centrifugals", name: "Batch Centrifugals", category: "Sugar Mill & Process Equipment", description: "Parts and automation support for batch centrifugal machines used in sugar mill operations.", applications: ["Batch sugar processing", "Centrifugal control", "Machine maintenance"], industries: ["sugar-mills"], brands: ["Omron", "Fuji Electric", "Hohner Encoders"] },
  { slug: "continuous-centrifugals", name: "Continuous Centrifugals", category: "Sugar Mill & Process Equipment", description: "Electrical, automation and measurement parts for continuous centrifugal sugar mill equipment.", applications: ["Continuous sugar processing", "Speed feedback", "Process automation"], industries: ["sugar-mills"], brands: ["Omron", "Lika Electronics", "Fuji Electric"] },

  { slug: "circuit-breakers", name: "Circuit Breakers", category: "Electrical Components", description: "MCCB, MCB and MPCB protection devices for control panels and machinery.", applications: ["Panel protection", "Motor protection", "Distribution boards"], industries: ["sugar-mills", "cement-plants", "fertilizer-industry"], brands: ["Eaton", "Fuji Electric"] },
  { slug: "magnetic-contactors", name: "Magnetic Contactors & Overload Relays", category: "Electrical Components", description: "Magnetic contactors and thermal overload relays for motor switching and protection.", applications: ["Motor starters", "Pump panels", "Crane panels"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Fuji Electric", "Eaton"] },
  { slug: "relays", name: "Relays", category: "Electrical Components", description: "Industrial control, monitoring, phase, voltage and thermistor relays for panels and machinery.", applications: ["Motor protection", "Voltage supervision", "Panel alarms"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Eaton", "Carlo Gavazzi", "Omron"] },
  { slug: "monitoring-relays", name: "Monitoring Relays", category: "Electrical Components", description: "Phase, voltage, thermistor and process monitoring relays.", applications: ["Motor protection", "Voltage supervision", "Panel alarms"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Eaton", "Carlo Gavazzi"] },
  { slug: "panels", name: "Panels", category: "Electrical Components", description: "Panel components and supply support for control panels, motor control centers and machine panels.", applications: ["Control panel assembly", "MCC panels", "Automation panels"], industries: ["textile-mills", "food-processing", "fertilizer-industry"], brands: ["Fuji Electric", "Eaton", "Omron"] },
  { slug: "dol-starters", name: "DOL & Starters", category: "Electrical Components", description: "Direct-on-line starters and control gear for industrial motors.", applications: ["Motor starting", "Pump control", "Machine panels"], industries: ["textile-mills", "food-processing", "fertilizer-industry"], brands: ["Fuji Electric", "Eaton"] },

  { slug: "solenoid-valves", name: "Solenoid Valves", category: "Valves & Flow Control", description: "Industrial solenoid valves for air, water, oil, gas and burner control applications.", applications: ["Fluid control", "Burner systems", "Pneumatic actuation"], industries: ["food-processing", "textile-mills", "cement-plants"], brands: ["Brahma", "Cofi Ignitions", "Huba Control"] },
  { slug: "control-valves", name: "Control Valves", category: "Valves & Flow Control", description: "Control valve sourcing for process flow, pressure and industrial fluid regulation.", applications: ["Process regulation", "Flow control", "Plant instrumentation"], industries: ["fertilizer-industry", "food-processing", "pharmaceutical-plants"], brands: ["Huba Control", "Carlo Gavazzi"] },
  { slug: "actuators", name: "Actuators", category: "Valves & Flow Control", description: "Electrical and pneumatic actuators used with valves, dampers and process control equipment.", applications: ["Valve actuation", "Damper control", "Machine automation"], industries: ["cement-plants", "food-processing", "fertilizer-industry"], brands: ["Omron", "Carlo Gavazzi"] },
  { slug: "flow-switches", name: "Flow Switches", category: "Valves & Flow Control", description: "Air and water flow switches for equipment protection and process monitoring.", applications: ["Cooling water checks", "Air flow supervision", "Pump systems"], industries: ["cement-plants", "food-processing"], brands: ["Carlo Gavazzi", "Huba Control"] },

  { slug: "sensors", name: "Industrial Sensors", category: "Sensors", description: "Proximity, photoelectric, ultrasonic, area, fiber optic and fork sensors.", applications: ["Object detection", "Position sensing", "Conveyor automation"], industries: ["textile-mills", "food-processing", "cement-plants"], brands: ["Omron", "Datasensing", "Carlo Gavazzi", "Xecro"] },
  { slug: "proximity-sensors", name: "Proximity Sensors", category: "Sensors", description: "Inductive and capacitive proximity sensors for machine position and object detection.", applications: ["Machine sensing", "Conveyor detection", "Limit replacement"], industries: ["textile-mills", "food-processing", "sugar-mills"], brands: ["Omron", "Datasensing", "Xecro"] },
  { slug: "photoelectric-sensors", name: "Photoelectric Sensors", category: "Sensors", description: "Photoelectric sensors for non-contact detection in packaging, conveyors and automation systems.", applications: ["Object detection", "Counting", "Packaging lines"], industries: ["food-processing", "textile-mills", "pharmaceutical-plants"], brands: ["Omron", "Datasensing"] },
  { slug: "ultrasonic-sensors", name: "Ultrasonic Sensors", category: "Sensors", description: "Ultrasonic sensors for distance, level and object detection where optical sensing is difficult.", applications: ["Distance sensing", "Level detection", "Object detection"], industries: ["cement-plants", "food-processing", "fertilizer-industry"], brands: ["Datasensing", "Carlo Gavazzi"] },
  { slug: "fiber-optic-sensors", name: "Fiber Optic Sensors", category: "Sensors", description: "Fiber optic sensors and amplifiers for compact or difficult industrial sensing points.", applications: ["Small object detection", "Restricted machine spaces", "Fast sensing"], industries: ["pharmaceutical-plants", "food-processing", "textile-mills"], brands: ["Omron", "Datasensing"] },

  { slug: "safety-relays", name: "Safety Relays", category: "Safety Systems", description: "Safety relays, controllers and non-contact safety sensors for machinery protection.", applications: ["Emergency stop circuits", "Safety gates", "Machine guarding"], industries: ["textile-mills", "pharmaceutical-plants", "food-processing"], brands: ["Pilz", "Omron"] },
  { slug: "light-curtains", name: "Light Curtains", category: "Safety Systems", description: "Safety light curtains and machine guarding sensors for operator protection.", applications: ["Machine guarding", "Press safety", "Access protection"], industries: ["textile-mills", "food-processing", "pharmaceutical-plants"], brands: ["Pilz", "Datasensing", "Omron"] },
  { slug: "gas-detection", name: "Gas Detection", category: "Safety Systems", description: "Gas detection and combustion safety components for industrial process and burner systems.", applications: ["Combustion safety", "Plant safety", "Gas monitoring"], industries: ["food-processing", "cement-plants", "fertilizer-industry"], brands: ["Brahma", "Cofi Ignitions"] },
  { slug: "safety-sensors", name: "Safety Sensors", category: "Safety Systems", description: "Non-contact safety sensors, safety switches and machine safety detection components.", applications: ["Safety doors", "Guard monitoring", "Machine protection"], industries: ["textile-mills", "pharmaceutical-plants", "food-processing"], brands: ["Pilz", "Omron", "Datasensing"] },

  { slug: "plc", name: "PLCs", category: "Control Systems", description: "Programmable logic controllers for plant automation, machine control and replacement panels.", applications: ["Machine automation", "Process control", "Panel upgrades"], industries: ["sugar-mills", "textile-mills", "pharmaceutical-plants"], brands: ["Omron", "Fuji Electric"] },
  { slug: "hmis", name: "HMIs", category: "Control Systems", description: "Human-machine interfaces for operator control, machine monitoring and automation panels.", applications: ["Operator panels", "Machine monitoring", "Process control"], industries: ["sugar-mills", "textile-mills", "food-processing"], brands: ["Omron", "Fuji Electric"] },
  { slug: "scada", name: "SCADA", category: "Control Systems", description: "SCADA components and automation hardware support for process supervision systems.", applications: ["Plant supervision", "Data monitoring", "Process dashboards"], industries: ["sugar-mills", "fertilizer-industry", "pharmaceutical-plants"], brands: ["Omron", "Fuji Electric"] },
  { slug: "io-modules", name: "IO Modules", category: "Control Systems", description: "Digital and analog I/O modules for PLC expansion and machine automation systems.", applications: ["PLC expansion", "Signal interface", "Panel upgrades"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Omron", "Fuji Electric"] },
  { slug: "timers-counters", name: "Timers & Counters", category: "Control Systems", description: "Industrial timers and counters for automation panels and machine sequencing.", applications: ["Batch counting", "Delay timing", "Control sequencing"], industries: ["textile-mills", "food-processing"], brands: ["Omron", "Shinko"] },

  { slug: "encoders", name: "Rotary & Linear Encoders", category: "Encoders & Measurement", description: "Rotary and linear encoder sourcing for speed, position and synchronization.", applications: ["Centrifugal machines", "Conveyors", "Position feedback"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Hohner Encoders", "Lika Electronics"] },
  { slug: "rotary-encoders", name: "Rotary Encoders", category: "Encoders & Measurement", description: "Rotary encoders for speed, shaft position and machine feedback systems.", applications: ["Speed feedback", "Position sensing", "Centrifugal machines"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["Hohner Encoders", "Lika Electronics"] },
  { slug: "linear-encoders", name: "Linear Encoders", category: "Encoders & Measurement", description: "Linear encoders and position measurement parts for industrial automation systems.", applications: ["Linear position feedback", "Machine measurement", "Automation feedback"], industries: ["textile-mills", "cement-plants", "sugar-mills"], brands: ["Lika Electronics", "Hohner Encoders"] },

  { slug: "cables", name: "Cables", category: "Accessories", description: "Industrial cables including PVC/PVC copper conductor cable and machine wiring accessories.", applications: ["Industrial wiring", "Control panels", "Machine electrical work"], industries: ["sugar-mills", "textile-mills", "cement-plants"], brands: ["General Industrial"] },
  { slug: "connectors", name: "Connectors", category: "Accessories", description: "Industrial connectors for sensors, control panels, machines and instrumentation wiring.", applications: ["Sensor wiring", "Panel wiring", "Machine connections"], industries: ["textile-mills", "food-processing", "cement-plants"], brands: ["Omron", "Datasensing"] },
  { slug: "terminal-blocks", name: "Terminal Blocks", category: "Accessories", description: "Terminal blocks and wiring accessories for industrial panels and machine control systems.", applications: ["Panel wiring", "Signal termination", "Control cabinets"], industries: ["sugar-mills", "textile-mills", "fertilizer-industry"], brands: ["General Industrial"] },

  { slug: "vfds", name: "VFDs", category: "Drives & Motion", description: "Variable frequency drives for motor speed control, process control and energy saving applications.", applications: ["Motor speed control", "Pump control", "Conveyor control"], industries: ["sugar-mills", "cement-plants", "textile-mills"], brands: ["Fuji Electric", "Eaton"] },
  { slug: "servo-systems", name: "Servo Systems", category: "Drives & Motion", description: "Servo drives, motors and motion components for precise industrial machine control.", applications: ["Motion control", "Positioning systems", "Machine automation"], industries: ["textile-mills", "food-processing", "pharmaceutical-plants"], brands: ["Omron", "Fuji Electric"] },
  { slug: "soft-starters", name: "Soft Starters", category: "Drives & Motion", description: "Soft starters for controlled motor starting and reduced electrical stress in industrial plants.", applications: ["Motor starting", "Pump systems", "Conveyor systems"], industries: ["cement-plants", "sugar-mills", "fertilizer-industry"], brands: ["Eaton", "Fuji Electric"] },

  { slug: "pressure-switches", name: "Pressure Switches & Transmitters", category: "Process Instrumentation", description: "Pressure switches and transmitters for air, water, oil, steam and process fluids.", applications: ["Pump protection", "Process measurement", "Hydraulic systems"], industries: ["pharmaceutical-plants", "food-processing", "fertilizer-industry"], brands: ["Eaton", "Huba Control", "Fantini Cosmi"] },
  { slug: "flow-instrumentation", name: "Flow", category: "Process Instrumentation", description: "Flow transmitters, switches and monitoring components for industrial process applications.", applications: ["Flow monitoring", "Pump protection", "Process control"], industries: ["food-processing", "fertilizer-industry", "cement-plants"], brands: ["Huba Control", "Carlo Gavazzi", "Datexel"] },
  { slug: "temperature-instrumentation", name: "Temperature", category: "Process Instrumentation", description: "Temperature controllers, indicators, transmitters and process measurement components.", applications: ["Temperature control", "Process indication", "Control loops"], industries: ["pharmaceutical-plants", "food-processing", "textile-mills"], brands: ["Shinko", "Ascon Tecnologic", "Datexel"] },
  { slug: "level-switches", name: "Level", category: "Process Instrumentation", description: "Float switches, floatless level relays, electrode holders and rotary level controls.", applications: ["Tank level control", "Silo level detection", "Pump automation"], industries: ["food-processing", "cement-plants", "fertilizer-industry"], brands: ["Riko Float Switches", "Carlo Gavazzi"] },
  { slug: "gas-combustion", name: "Gas / Combustion", category: "Process Instrumentation", description: "Burner controllers, ignition relays, solenoid valves, UV sensors and combustion monitoring parts.", applications: ["Boiler burners", "Industrial ovens", "Flame supervision"], industries: ["food-processing", "textile-mills", "cement-plants"], brands: ["Brahma", "Cofi Ignitions"] },
  { slug: "burner-controls", name: "Burner Controls", category: "Process Instrumentation", description: "Burner controllers, ignition relays, solenoid valves, UV sensors and photo-diodes.", applications: ["Boiler burners", "Industrial ovens", "Flame supervision"], industries: ["food-processing", "textile-mills", "cement-plants"], brands: ["Brahma", "Cofi Ignitions"] },
  { slug: "transmitters", name: "Transmitters & Process Controllers", category: "Process Instrumentation", description: "Flow, pressure, temperature and process transmitters and controllers.", applications: ["Process indication", "Control loops", "Plant instrumentation"], industries: ["pharmaceutical-plants", "fertilizer-industry", "food-processing"], brands: ["Datexel", "Huba Control", "Ascon Tecnologic"] }
];
